;This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.28"

; Modules
projects[addressfield][version] = "1.0-beta5"

projects[ctools][version] = "1.4"

projects[commerce][version] = "1.9"

projects[commerce_cart_expiration][version] = "1.1"

projects[date][version] = "2.7"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.0"

projects[libraries][version] = "2.2"

projects[rooms][type] = "module"
projects[rooms][download][type] = "git"
projects[rooms][download][url] = "git@github.com:BluesparkLabs/DrupalRoomsModule.git"
projects[rooms][directory_name] = "rooms"


projects[rules][version] = "2.7"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[rooms_fullcalendar][download][type] = "file"
libraries[rooms_fullcalendar][download][url] = "http://www.drupalrooms.com/sites/default/files/fullcalendar-1.5.4.zip"
libraries[rooms_fullcalendar][directory_name] = "rooms_fullcalendar"
libraries[rooms_fullcalendar][type] = "library"
